# .github/workflows/use-secret.yml
name: Use Secret Demo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_branch:
        description: "Fork branch name"
        required: true
      pr_repo:
        description: "Fork repo (username/repo)"
        required: true

jobs:
  secure-job:
    runs-on: ubuntu-latest
    environment: secure  # 🔐 this triggers required approval
    steps:
      - name: Checkout fork code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.pr_repo }}
          ref: ${{ github.event.inputs.pr_branch }}

      - name: Use secret (after approval)
        run: |
          echo "Using secret: $SECRET"
        env:
          SECRET: ${{ secrets.SECRET }}
